### ISSUE TITLE
Add Esent based Eventstore

### ISSUE THREAD

**Issue by DanielEggers** [ralfw/NSimpleEventstore#2]
[ManagedEsent ](https://github.com/microsoft/ManagedEsent/blob/master/Documentation/PersistentDictionaryDocumentation.md) is a very convenient interface to the Windows built in Esent database and would be good fit as a persistent backend.
Advantages: fast, reliable, only few files are written to disk and no administration.
Limitations: Windows only, number of events per collection limited to 2^31
Would you accept a PR?

**Comment by ralfw** [comment]
That's a great idea! Sure I would accept a PR. (I just would have a hard time running the tests because I don't use Windows anymore.)

**Comment by ralfw** [comment]
Thanks for your contribution of the Esent repository! Hope this is working well on Windows ;-)
